version: '3'

services:
  tmus-qr:
    container_name: tmus-qr
    build:
      context: .
      dockerfile: .dockerfile
#    image: arm64v8/node
#    restart: unless-stopped
#    env_file: .env
#    environment:
#      - MONGO_USERNAME=$MONGO_USERNAME
#      - MONGO_PASSWORD=$MONGO_PASSWORD
#      - MONGO_HOSTNAME=db
#      - MONGO_PORT=$MONGO_PORT
#      - MONGO_DB=$MONGO_DB
    ports:
      # container : host
      - "3000:3000"
    volumes:
      - .:/usr/src/
      - ./node_modules:/usr/src/node_modules
      - /usr/src/.next
