version: '3'

services:
  qr:
    container_name: qr
    build:
      context: .
      dockerfile: .dockerfile
#    image: arm64v8/node
#    restart: unless-stopped
#    env_file: .env
    ports:
      # container : host
      - "3000:3000"
    volumes:
      - .:/usr/src/
      - ./node_modules:/usr/src/node_modules
      - /usr/src/.next
