version: '3'

services:
  tmus-qr:
    container_name: tmus-qr
    networks:
      - frontend
    build:
      context: .
      dockerfile: .dockerfile
#    image: arm64v8/node
#    restart: unless-stopped
#    env_file: .env
#    environment:
#      - MONGO_USERNAME=$MONGO_USERNAME
#      - MONGO_PASSWORD=$MONGO_PASSWORD
#      - MONGO_HOSTNAME=db
#      - MONGO_PORT=$MONGO_PORT
#      - MONGO_DB=$MONGO_DB
#    ports:
#      # container : host
#      - "3000:3000"
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
      - /usr/src/.next
    networks:
      - frontend
    labels:
      - “traefik.enable=true”
      - “traefik.http.routers.tmus-qr.rule=Host(`qr.sterlingholt.tech`)”
      - “traefik.http.routers.tmus-qr.entrypoints=http, https”
      - "traefik.http.routers.tmus-qr-secure.service=tmus-qr"
      - "traefik.http.services.tmus-qr.loadbalancer.server.port=3000"
      - "traefik.docker.network=frontend"
      #- “traefik.http.routers.tmus-qr.tls.certresolver=le”
      # - "whatever code to specify container port for traefik to listen to"

networks:
  frontend:
    external: true
